-- MySQL Script generated by MySQL Workbench
-- Wed Nov 12 19:20:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inmobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inmobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inmobiliaria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `inmobiliaria` ;

-- -----------------------------------------------------
-- Table `inmobiliaria`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`persona` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(20) NOT NULL,
  `cod_personal` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(120) NOT NULL,
  `tel_fijo` VARCHAR(30) NULL DEFAULT NULL,
  `movil` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `cod_personal` (`cod_personal` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`antiguedad_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`antiguedad_categoria` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`antiguedad_categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`anunciante_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`anunciante_tipo` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`anunciante_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`disposicion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`disposicion` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`disposicion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`inmueble_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`inmueble_tipo` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`inmueble_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`zona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`zona` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`zona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`inmueble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`inmueble` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`inmueble` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_id` INT NOT NULL,
  `codigo_inmueble` VARCHAR(50) NOT NULL,
  `zona_id` INT NOT NULL,
  `provincia` VARCHAR(80) NOT NULL,
  `ciudad_localidad` VARCHAR(120) NOT NULL,
  `barrio` VARCHAR(120) NULL DEFAULT NULL,
  `direccion` VARCHAR(180) NOT NULL,
  `latitud` DECIMAL(9,6) NULL DEFAULT NULL,
  `longitud` DECIMAL(9,6) NULL DEFAULT NULL,
  `superficie_total_m2` DECIMAL(10,2) NULL DEFAULT NULL,
  `superficie_cubierta_m2` DECIMAL(10,2) NULL DEFAULT NULL,
  `ambientes` INT NULL DEFAULT NULL,
  `dormitorios` INT NULL DEFAULT NULL,
  `banos` INT NULL DEFAULT NULL,
  `cocheras` INT NULL DEFAULT NULL,
  `disposicion_id` INT NULL DEFAULT NULL,
  `antiguedad_categoria_id` INT NULL DEFAULT NULL,
  `anio_construccion` INT NULL DEFAULT NULL,
  `anunciante_tipo_id` INT NOT NULL,
  `anunciante_detalle` VARCHAR(120) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `precio` DECIMAL(12,2) NULL DEFAULT NULL,
  `moneda` ENUM('ARS', 'USD') NULL DEFAULT 'ARS',
  `disponible` TINYINT(1) NULL DEFAULT '1',
  `tipo_operacion` ENUM('venta', 'alquiler') NOT NULL DEFAULT 'venta' COMMENT 'Tipo de operación: venta o alquiler',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_inmueble` (`codigo_inmueble` ASC) VISIBLE,
  INDEX `fk_inmueble_tipo` (`tipo_id` ASC) VISIBLE,
  INDEX `idx_inmueble_zona` (`zona_id` ASC) VISIBLE,
  INDEX `idx_inmueble_disposicion` (`disposicion_id` ASC) VISIBLE,
  INDEX `idx_inmueble_antiguedad` (`antiguedad_categoria_id` ASC) VISIBLE,
  INDEX `idx_inmueble_anunciante` (`anunciante_tipo_id` ASC) VISIBLE,
  INDEX `idx_inmueble_amb_dorm_bano` (`ambientes` ASC, `dormitorios` ASC, `banos` ASC) VISIBLE,
  INDEX `idx_inmueble_sup_total` (`superficie_total_m2` ASC) VISIBLE,
  INDEX `idx_inmueble_lat_lon` (`latitud` ASC, `longitud` ASC) VISIBLE,
  CONSTRAINT `fk_inmueble_antig`
    FOREIGN KEY (`antiguedad_categoria_id`)
    REFERENCES `inmobiliaria`.`antiguedad_categoria` (`id`),
  CONSTRAINT `fk_inmueble_anunc`
    FOREIGN KEY (`anunciante_tipo_id`)
    REFERENCES `inmobiliaria`.`anunciante_tipo` (`id`),
  CONSTRAINT `fk_inmueble_dispo`
    FOREIGN KEY (`disposicion_id`)
    REFERENCES `inmobiliaria`.`disposicion` (`id`),
  CONSTRAINT `fk_inmueble_tipo`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `inmobiliaria`.`inmueble_tipo` (`id`),
  CONSTRAINT `fk_inmueble_zona`
    FOREIGN KEY (`zona_id`)
    REFERENCES `inmobiliaria`.`zona` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`alquiler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`alquiler` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`alquiler` (
  `inmueble_id` INT NOT NULL,
  `nro_alquiler` INT NOT NULL,
  `agente_id` INT NOT NULL,
  `inquilino_id` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `precio_mensual` DECIMAL(12,2) NOT NULL,
  `estado` ENUM('VIGENTE', 'FINALIZADO', 'RESCINDIDO') NULL DEFAULT NULL,
  PRIMARY KEY (`inmueble_id`, `nro_alquiler`),
  INDEX `idx_alquiler_agente` (`agente_id` ASC) VISIBLE,
  INDEX `idx_alquiler_inquilino` (`inquilino_id` ASC) VISIBLE,
  CONSTRAINT `fk_alq_agente`
    FOREIGN KEY (`agente_id`)
    REFERENCES `inmobiliaria`.`persona` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_alq_inmueble`
    FOREIGN KEY (`inmueble_id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_alq_inquilino`
    FOREIGN KEY (`inquilino_id`)
    REFERENCES `inmobiliaria`.`persona` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`amenidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`amenidad` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`amenidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`casa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`casa` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`casa` (
  `id` INT NOT NULL,
  `ambientes_extra` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_casa_inmueble`
    FOREIGN KEY (`id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`compra` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inmueble_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `cod_compra` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_compra` (`cod_compra` ASC) VISIBLE,
  INDEX `fk_compra_inmueble` (`inmueble_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_inmueble`
    FOREIGN KEY (`inmueble_id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`compra_titular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`compra_titular` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`compra_titular` (
  `compra_id` INT NOT NULL,
  `persona_id` INT NOT NULL,
  `porcentaje` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`compra_id`, `persona_id`),
  INDEX `fk_ct_persona` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_ct_compra`
    FOREIGN KEY (`compra_id`)
    REFERENCES `inmobiliaria`.`compra` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ct_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `inmobiliaria`.`persona` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`consulta` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inmueble_id` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `mensaje` TEXT NOT NULL,
  `tipo_consulta` ENUM('INFORMACION', 'VISITA', 'COTIZACION', 'OTRO') NULL DEFAULT 'INFORMACION',
  `estado` ENUM('PENDIENTE', 'ATENDIDA', 'CANCELADA') NULL DEFAULT 'PENDIENTE',
  `fecha_consulta` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `inmueble_id` (`inmueble_id` ASC) VISIBLE,
  CONSTRAINT `consulta_ibfk_1`
    FOREIGN KEY (`inmueble_id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`departamento` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`departamento` (
  `id` INT NOT NULL,
  `cod_departamento` VARCHAR(50) NOT NULL,
  `planta` VARCHAR(20) NULL DEFAULT NULL,
  `puerta` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_departamento` (`cod_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_depto_inmueble`
    FOREIGN KEY (`id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`usuario` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NULL DEFAULT NULL,
  `email` VARCHAR(120) NOT NULL,
  `google_id` VARCHAR(255) NULL DEFAULT NULL,
  `auth_provider` ENUM('local', 'google') NULL DEFAULT 'local',
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `foto_perfil` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `google_id` (`google_id` ASC) VISIBLE,
  INDEX `fk_usuario_persona` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `inmobiliaria`.`persona` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`favorito` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`favorito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `inmueble_id` INT NOT NULL,
  `fecha_agregado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_usuario_inmueble` (`usuario_id` ASC, `inmueble_id` ASC) VISIBLE,
  INDEX `idx_favorito_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_favorito_inmueble` (`inmueble_id` ASC) VISIBLE,
  CONSTRAINT `favorito_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `inmobiliaria`.`usuario` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `favorito_ibfk_2`
    FOREIGN KEY (`inmueble_id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`garaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`garaje` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`garaje` (
  `id` INT NOT NULL,
  `numero_garaje` VARCHAR(30) NOT NULL,
  `planta` VARCHAR(20) NULL DEFAULT NULL,
  `departamento_asociado_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_garaje_depto` (`departamento_asociado_id` ASC) VISIBLE,
  CONSTRAINT `fk_garaje_depto`
    FOREIGN KEY (`departamento_asociado_id`)
    REFERENCES `inmobiliaria`.`departamento` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_garaje_inmueble`
    FOREIGN KEY (`id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`inmueble_amenidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`inmueble_amenidad` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`inmueble_amenidad` (
  `inmueble_id` INT NOT NULL,
  `amenidad_id` INT NOT NULL,
  PRIMARY KEY (`inmueble_id`, `amenidad_id`),
  INDEX `fk_inm_amen_amenidad` (`amenidad_id` ASC) VISIBLE,
  CONSTRAINT `fk_inm_amen_amenidad`
    FOREIGN KEY (`amenidad_id`)
    REFERENCES `inmobiliaria`.`amenidad` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_inm_amen_inmueble`
    FOREIGN KEY (`inmueble_id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`local` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`local` (
  `id` INT NOT NULL,
  `uso` VARCHAR(80) NOT NULL,
  `tiene_servicio` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_local_inmueble`
    FOREIGN KEY (`id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`pago_alquiler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`pago_alquiler` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`pago_alquiler` (
  `inmueble_id` INT NOT NULL,
  `nro_alquiler` INT NOT NULL,
  `anio` INT NOT NULL,
  `mes` INT NOT NULL,
  `valor` DECIMAL(12,2) NOT NULL,
  `fecha_pago` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`inmueble_id`, `nro_alquiler`, `anio`, `mes`),
  CONSTRAINT `fk_pago_alquiler`
    FOREIGN KEY (`inmueble_id` , `nro_alquiler`)
    REFERENCES `inmobiliaria`.`alquiler` (`inmueble_id` , `nro_alquiler`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`persona_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`persona_rol` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`persona_rol` (
  `persona_id` INT NOT NULL,
  `rol` ENUM('CLIENTE', 'TRABAJADOR') NOT NULL,
  PRIMARY KEY (`persona_id`, `rol`),
  CONSTRAINT `fk_persona_rol_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `inmobiliaria`.`persona` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`rol_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`rol_app` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`rol_app` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`session_refresh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`session_refresh` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`session_refresh` (
  `id` CHAR(36) NOT NULL,
  `usuario_id` INT NOT NULL,
  `refresh_token` VARCHAR(255) NOT NULL,
  `expira_en` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `refresh_token` (`refresh_token` ASC) VISIBLE,
  INDEX `fk_session_usuario` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `inmobiliaria`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`usuario_rol_app`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`usuario_rol_app` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`usuario_rol_app` (
  `usuario_id` INT NOT NULL,
  `rol_app_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `rol_app_id`),
  INDEX `fk_ur_rol` (`rol_app_id` ASC) VISIBLE,
  CONSTRAINT `fk_ur_rol`
    FOREIGN KEY (`rol_app_id`)
    REFERENCES `inmobiliaria`.`rol_app` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_ur_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `inmobiliaria`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inmobiliaria`.`visita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inmobiliaria`.`visita` ;

CREATE TABLE IF NOT EXISTS `inmobiliaria`.`visita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inmueble_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `agente_id` INT NULL DEFAULT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visita_inmueble` (`inmueble_id` ASC) VISIBLE,
  INDEX `fk_visita_cliente` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_visita_agente` (`agente_id` ASC) VISIBLE,
  CONSTRAINT `fk_visita_agente`
    FOREIGN KEY (`agente_id`)
    REFERENCES `inmobiliaria`.`persona` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_visita_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `inmobiliaria`.`persona` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_visita_inmueble`
    FOREIGN KEY (`inmueble_id`)
    REFERENCES `inmobiliaria`.`inmueble` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `inmobiliaria`;

DELIMITER $$

USE `inmobiliaria`$$
DROP TRIGGER IF EXISTS `inmobiliaria`.`trg_alquiler_roles_bi` $$
USE `inmobiliaria`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `inmobiliaria`.`trg_alquiler_roles_bi`
BEFORE INSERT ON `inmobiliaria`.`alquiler`
FOR EACH ROW
BEGIN
  IF NOT EXISTS (SELECT 1 FROM persona_rol pr WHERE pr.persona_id = NEW.agente_id AND pr.rol = 'TRABAJADOR') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'agente_id debe tener rol TRABAJADOR';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM persona_rol pr WHERE pr.persona_id = NEW.inquilino_id AND pr.rol = 'CLIENTE') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'inquilino_id debe tener rol CLIENTE';
  END IF;
END$$


USE `inmobiliaria`$$
DROP TRIGGER IF EXISTS `inmobiliaria`.`trg_alquiler_roles_bu` $$
USE `inmobiliaria`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `inmobiliaria`.`trg_alquiler_roles_bu`
BEFORE UPDATE ON `inmobiliaria`.`alquiler`
FOR EACH ROW
BEGIN
  IF NOT EXISTS (SELECT 1 FROM persona_rol pr WHERE pr.persona_id = NEW.agente_id AND pr.rol = 'TRABAJADOR') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'agente_id debe tener rol TRABAJADOR';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM persona_rol pr WHERE pr.persona_id = NEW.inquilino_id AND pr.rol = 'CLIENTE') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'inquilino_id debe tener rol CLIENTE';
  END IF;
END$$


USE `inmobiliaria`$$
DROP TRIGGER IF EXISTS `inmobiliaria`.`trg_visita_cliente_bi` $$
USE `inmobiliaria`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `inmobiliaria`.`trg_visita_cliente_bi`
BEFORE INSERT ON `inmobiliaria`.`visita`
FOR EACH ROW
BEGIN
  IF NOT EXISTS (SELECT 1 FROM persona_rol pr WHERE pr.persona_id = NEW.cliente_id AND pr.rol = 'CLIENTE') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'cliente_id debe tener rol CLIENTE';
  END IF;
END$$


USE `inmobiliaria`$$
DROP TRIGGER IF EXISTS `inmobiliaria`.`trg_visita_cliente_bu` $$
USE `inmobiliaria`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `inmobiliaria`.`trg_visita_cliente_bu`
BEFORE UPDATE ON `inmobiliaria`.`visita`
FOR EACH ROW
BEGIN
  IF NOT EXISTS (SELECT 1 FROM persona_rol pr WHERE pr.persona_id = NEW.cliente_id AND pr.rol = 'CLIENTE') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'cliente_id debe tener rol CLIENTE';
  END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
